### ISSUE TITLE
Updates 6/18/2020

### ISSUE THREAD

**Issue by jlopezseslocfcu** [jlopezseslocfcu/drupal-site-updates-notes#1]

**Comment by kclarkSESLOC** [comment]
Pages on staging that are not to go live yet: 

https://seslocstg.prod.acquia-sites.com/loans/fraud-monitoring-service

https://seslocstg.prod.acquia-sites.com/loans/visa-signature-rewards-credit-card

**Comment by kclarkSESLOC** [comment]
Do I need to review Dev, or just staging?

**Comment by jlopezseslocfcu** [comment]
Hi Kara,

Just staging. Dev should not be getting updated.

**Comment by jlopezseslocfcu** [comment]
Kara, have those 2 pages been worked on today or will they be worked on Monday morning? I was thinking I set them to un-published, so when the changes get pushed, if they end up on live they will not be visible to anyone who isn't admin.
